### ISSUE TITLE
No newline at the end of the output

### ISSUE THREAD

**Issue by lionkor** [sla-ppy/001-pass_gen#1]
After the program terminates, it does not put a newline at the end of the output:

![image](https://user-images.githubusercontent.com/29932116/116916432-965bf400-ac4d-11eb-889f-54fe4b4cbb25.png)

It would be cool if it had the newline at the end so that the output looks neater!

**Comment by sla-ppy** [comment]
thanks Lion!
this issue has been closed as the problem has been fixed.

your great dedication to this project earned the community which includes you (and well... you.) a hidden easter egg.
i urge you to find it without looking at the source code.
